### ISSUE TITLE
Useful to include in README

### ISSUE THREAD

**Issue by jacky-lam** [JSqlServerBulkInsert/JSqlServerBulkInsert#15]
Would be helpful to explain in the README, under the `Mapping` section:

- **All fields must be mapped**, including the auto-generated fields.
- Fields must be mapped in the **same order** as the table.

**Comment by bytefish** [comment]
@jacky-lam I have updated the README with your advices. In Issue #17 a feature has been added to validate the Metadata (so it is checked, that all columns are matched) and the order of the Columns do not matter anymore, because the Mappings will be ordered when inserting to SQL Server.

Thanks for your help! 👍
